export const siteConfig = {
  brandName: "FAD-DIS",
  tagline: "Votre supermarché de proximité en ligne",
  currency: "FCFA",
  phone: "+223 76 68 62 62 ",
  email: "contact@faddis.com",
  address: "Adresse Faladiè du Gouverneur  à 100M  du centre d'impôt",
  orangeMoneyMerchantCode: "552573",
};

export const mainCategories = [
  {
    id: "fruits-legumes",
    name: "Fruits & Légumes",
    description: "Produits frais, fruits secs, légumes frais et sélection bio.",
    image: "/images/categories/fruits-et-légumes.png",
    subcategories: [
      "Fruits frais",
      "Légumes frais",
      "Produits bio",
      "Fruits secs & oléagineux",
    ],
  },
  {
    id: "boucherie-charcuterie",
    name: "Boucherie & Charcuterie",
    description: "Viandes fraîches, charcuterie, produits traiteur et alternatives végétales.",
    image: "/images/categories/boucherie.png",
    subcategories: [
      "Viande fraîche (bœuf, poulet, porc, agneau)",
      "Charcuterie (saucisses, pâtés)",
      "Produits traiteur",
      "Alternatives végétariennes/vegan",
    ],
  },
  {
    id: "poissonnerie-fruits-mer",
    name: "Poissonnerie & Fruits de Mer",
    description: "Poissons frais, fruits de mer et produits surgelés.",
    image: "/images/categories/poissonnerie.png",
    subcategories: [
      "Poissons frais",
      "Fruits de mer",
      "Produits surgelés",
    ],
  },
  {
    id: "epicerie-salee",
    name: "Épicerie Salée",
    description: "Conserves, sauces, céréales, condiments et produits apéritifs.",
    image: "/images/categories/epicerie-salee-epices.png",
    subcategories: [
      "Conserves & sauces",
      "Pâtes, riz & céréales",
      "Produits apéritifs (chips, biscuits salés)",
      "Condiments & épices",
    ],
  },
  {
    id: "epicerie-sucree",
    name: "Épicerie Sucrée",
    description: "Biscuits, gâteaux, confiseries, confitures et produits pâtissiers.",
    image: "/images/categories/epicerie-sucrée.png",
    subcategories: [
      "Biscuits & gâteaux",
      "Chocolats & confiseries",
      "Miels, confitures & pâtes à tartiner",
      "Produits pour pâtisserie",
    ],
  },
  {
    id: "produits-laitiers-oeufs",
    name: "Produits Laitiers & Œufs",
    description: "Lait, boissons végétales, fromages, yaourts et œufs.",
    image: "/images/categories/laitier.png",
    subcategories: [
      "Lait & boissons végétales",
      "Fromages",
      "Yaourts & desserts lactés",
      "Œufs",
    ],
  },
  {
    id: "boissons",
    name: "Boissons",
    description: "Eaux, jus, smoothies, cafés, thés et boissons du quotidien.",
    image: "/images/categories/boisson.png",
    subcategories: [
      "Eau & boissons non alcoolisées",
      "Jus de fruits & smoothies",
      "Cafés & thés",
      "Vins & alcools",
    ],
  },
  {
    id: "boulangerie-patisserie",
    name: "Boulangerie & Pâtisserie",
    description: "Pain frais, viennoiseries et pâtisseries.",
    image: "/images/categories/boulangerie.png",
    subcategories: [
      "Pain frais & spécialités",
      "Viennoiseries",
      "Pâtisseries",
    ],
  },
  {
    id: "produits-surgeles",
    name: "Produits Surgelés",
    description: "Plats préparés, légumes, fruits et desserts glacés.",
    image: "/images/categories/produit-surgelé.png",
    subcategories: [
      "Plats préparés surgelés",
      "Légumes & fruits surgelés",
      "Glaces & desserts glacés",
    ],
  },
  {
    id: "hygène",
    name: "Hygène et Beauté",
    description: "Alimentation bio et produits d’entretien écologiques.",
    image: "/images/categories/hygème-beauté.png",
    subcategories: [
      "Alimentation bio",
      "Produits d’entretien écologiques",
    ],
  },
];

export const featuredProducts = [
  {
    id: "prod-1",
    name: "Belle France Nectar Multifruits",
    slug: "belle-france-nectar-multifruits",
    price: 1500,
    oldPrice: 1800,
    image: "/images/products/jus-multifruits.jpg",
    badge: "Top vente",
    unit: "1 L",
    category: "Boissons",
    categoryId: "boissons",
  },
  {
    id: "prod-2",
    name: "Maxwell House Qualité Filtre",
    slug: "maxwell-house-qualite-filtre",
    price: 4500,
    oldPrice: null,
    image: "/images/products/cafe-maxwell.jpg",
    badge: "Nouveau",
    unit: "110 tasses",
    category: "Boissons",
    categoryId: "boissons",
  },
  {
    id: "prod-3",
    name: "Presséa Nectar Goyave",
    slug: "pressea-nectar-goyave",
    price: 1600,
    oldPrice: null,
    image: "/images/products/jus.jpeg",
    badge: "Fraîcheur",
    unit: "1 L",
    category: "Boissons",
    categoryId: "boissons",
  },
  {
    id: "prod-4",
    name: "La Vache qui rit Original",
    slug: "la-vache-qui-rit-original",
    price: 2300,
    oldPrice: 2500,
    image: "/images/products/fromage-vache-qui-rit.jpg",
    badge: "Promo",
    unit: "8 portions",
    category: "Produits Laitiers & Œufs",
    categoryId: "produits-laitiers-oeufs",
  },
  {
    id: "prod-5",
    name: "Mélange de légumes surgelés",
    slug: "melange-legumes-surgeles",
    price: 3200,
    oldPrice: null,
    image: "/images/categories/produit-surgelé.jpg",
    badge: "Pratique",
    unit: "1 sachet",
    category: "Produits Surgelés",
    categoryId: "produits-surgeles",
  },
  {
    id: "prod-6",
    name: "Viande fraîche sélection",
    slug: "viande-fraiche-selection",
    price: 6800,
    oldPrice: null,
    image: "/images/categories/Boucherie.jpg",
    badge: "Fraîcheur",
    unit: "1 kg",
    category: "Boucherie & Charcuterie",
    categoryId: "boucherie-charcuterie",
  },
  {
    id: "prod-7",
    name: "Poissonnerie sélection marché",
    slug: "poissonnerie-selection-marche",
    price: 7900,
    oldPrice: null,
    image: "/images/products/poissonnerie.jpg",
    badge: "Arrivage",
    unit: "1 kg",
    category: "Poissonnerie & Fruits de Mer",
    categoryId: "poissonnerie",
  },
  {
    id: "prod-8",
    name: "Pain spécial boulangerie",
    slug: "pain-special-boulangerie",
    price: 900,
    oldPrice: 1100,
    image: "/images/categories/boulangerie.jpg",
    badge: "Du jour",
    unit: "1 pièce",
    category: "Boulangerie & Pâtisserie",
    categoryId: "boulangerie-patisserie",
  },
];

export const serviceHighlights = [
  {
    title: "Livraison rapide",
    description: "Commandez en ligne et recevez vos courses dans les meilleurs délais.",
  },
  {
    title: "Paiement Orange Money",
    description: "Paiement par code marchand et scan QR pour une expérience simple.",
  },
  {
    title: "Produits du quotidien",
    description: "Une sélection pensée pour les besoins réels des familles et commerces.",
  },
];

export const footerLinks = {
  boutique: ["Accueil", "Catégories", "Produits vedettes", "Promotions"],
  serviceClient: ["Contact", "Livraison", "Paiement", "FAQ"],
  informations: ["À propos", "Conditions générales", "Politique de confidentialité"],
};